import Link from "next/link";
import localFont from 'next/font/local';
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/marginals/navbar/Navbar";
import Footer from "@/components/marginals/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sprintura = localFont({
  src: '../fonts/sprintura-demo.regular.otf',
  variable: '--font-sprintura',
  weight: '900',
});

const thuast = localFont({
  src: '../fonts/thuast.demo.otf',
  variable: '--font-thuast',
  weight: '900',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`overflow-x-hidden ${geistSans.variable} ${geistMono.variable} ${sprintura.variable} ${thuast.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <Navbar />
          <main className="p-0">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
